// AUTO-GENERATED by stories/gaotai/generate_nodes.py — 勿手改。
// 源数据：stories/gaotai/terms.md
import type { TermCategoryInfo, TermDef } from "../../src/engine/types";

export const TERM_CATEGORIES: Record<string, TermCategoryInfo> = {
  "人物": { label: "人物", color: "#d4a24e" },
  "地点": { label: "地点", color: "#4fd1c5" },
  "器物": { label: "器物", color: "#f87171" },
  "概念": { label: "概念", color: "#a78bfa" },
};

export const TERMS: TermDef[] = [
  {"term": "高太公", "category": "人物", "meaning": "你。高老庄的庄主，七十岁，养女翠兰，招了个猪妖女婿。一辈子种地，一辈子按簿子上写的活。", "firstSeen": "Node_1_1", "related": ["翠兰", "八戒", "高老庄"]},
  {"term": "翠兰", "category": "人物", "meaning": "你的女儿。十四年前被猪妖强娶，如今独居高老庄，神思恍惚，谁也认不得。", "firstSeen": "Node_1_1", "related": ["高太公", "八戒", "春桃"]},
  {"term": "八戒", "category": "人物", "meaning": "你的女婿，猪悟能。原是掌管天河的天蓬元帅，投了猪胎，入赘高家，后随唐僧取经，得道成神。", "firstSeen": "Node_1_2", "related": ["高太公", "翠兰", "净坛使者", "天蓬元帅", "金钉耙"]},
  {"term": "净坛使者", "category": "人物", "meaning": "八戒取经后受的封号。享受十方供品——说白了，是替神佛收拾剩饭供品的差事。", "firstSeen": "Node_1_1", "related": ["八戒"]},
  {"term": "春桃", "category": "人物", "meaning": "高家的丫鬟，伺候翠兰，十四年前死于一场「瘟疫」。", "firstSeen": "Node_1_7", "related": ["翠兰", "高太公"]},
  {"term": "崔判官", "category": "人物", "meaning": "执掌生死簿的老判官，名珏，判了千年案。", "firstSeen": "Node_1_6", "related": ["生死簿", "判官印", "判官笔"]},
  {"term": "阎罗王", "category": "人物", "meaning": "十殿之主，生死轮回的看守，千年未离正殿。", "firstSeen": "Node_1_5", "related": ["阎罗殿", "生死簿"]},
  {"term": "孟婆", "category": "人物", "meaning": "忘川桥头的掌汤人，千年不变的微笑。", "firstSeen": "Node_2_3", "related": ["忘川", "孟婆汤"]},
  {"term": "二郎神", "category": "人物", "meaning": "天庭钦差，三尖两刃刀，半人半神，听调不听宣。", "firstSeen": "Node_2_7", "related": ["天条"]},
  {"term": "观音菩萨", "category": "人物", "meaning": "取经大计的主持者。「高老庄一难」这出戏，出自她手。", "firstSeen": "Node_1_7", "related": ["取经", "明怒尊者"]},
  {"term": "牛头马面", "category": "人物", "meaning": "阴间锁人的鬼差，一左一右，铁链加身。", "firstSeen": "Node_1_3", "related": ["黄泉路"]},
  {"term": "天蓬元帅", "category": "人物", "meaning": "八戒的前身，掌管天河的天将，酒后获罪，投了猪胎。", "firstSeen": "Node_1_5", "related": ["八戒"]},
  {"term": "高老庄", "category": "地点", "meaning": "你的庄子，种麦子、养猪、烧香、纳粮的地方。", "firstSeen": "Node_1_1", "related": ["高太公", "第二十四难"]},
  {"term": "黄泉路", "category": "地点", "meaning": "死人去往阴间的土路，没有回头路，路边开满红得发黑的花。", "firstSeen": "Node_1_3", "related": ["牛头马面"]},
  {"term": "忘川", "category": "地点", "meaning": "阴间的大河，桥下黑水滔滔，过了桥就是望乡台。", "firstSeen": "Node_1_3", "related": ["孟婆", "孟婆汤", "忘川水", "望乡台"]},
  {"term": "望乡台", "category": "地点", "meaning": "登台回望人间的地方，每个鬼都在这上面哭。", "firstSeen": "Node_1_4", "related": ["忘川"]},
  {"term": "阎罗殿", "category": "地点", "meaning": "阎罗王坐镇的正殿，生死簿在此审理。", "firstSeen": "Node_1_5", "related": ["阎罗王", "生死簿"]},
  {"term": "南天门", "category": "地点", "meaning": "天庭的门户，天兵列阵的地方。", "firstSeen": "Node_End_1", "related": ["凌霄宝殿"]},
  {"term": "凌霄宝殿", "category": "地点", "meaning": "玉帝临朝的地方，也是天兵最后的屏障。", "firstSeen": "Node_End_1", "related": ["南天门"]},
  {"term": "六道轮回", "category": "地点", "meaning": "鬼魂投胎转世的六条道，也是阴间秩序的地基。", "firstSeen": "Node_2_1", "related": ["生死簿", "轮回为猪"]},
  {"term": "生死簿", "category": "器物", "meaning": "记着天下所有活人死人的簿子。名字在簿上，命就在簿上；名字被抹，人就等于没活过。", "firstSeen": "Node_1_5", "related": ["崔判官", "判官印", "判官笔", "阳寿"]},
  {"term": "判官印", "category": "器物", "meaning": "能改生死簿的青玉印，天底下改命的唯一凭证。", "firstSeen": "Node_2_2", "related": ["崔判官", "生死簿"]},
  {"term": "判官笔", "category": "器物", "meaning": "崔判官执笔千年的笔，簿上的字都是它写的。", "firstSeen": "Node_1_5", "related": ["崔判官", "生死簿"]},
  {"term": "孟婆汤", "category": "器物", "meaning": "忘川桥头的汤，喝了就忘。一半给死人，一半给活人。", "firstSeen": "Node_2_3", "related": ["孟婆", "忘川"]},
  {"term": "忘川水", "category": "器物", "meaning": "灌进活人嘴里的忘川水，能把记忆连根拔了。", "firstSeen": "Node_1_7", "related": ["忘川", "孟婆汤"]},
  {"term": "灵幡", "category": "器物", "meaning": "你出殡用的白幡，幡上绣着一个「问」字，后来成了你的战旗。", "firstSeen": "Node_2_8", "related": ["高太公"]},
  {"term": "金钉耙", "category": "器物", "meaning": "八戒的本命家伙，当年在高老庄犁地，如今扛着上了战场。", "firstSeen": "Node_3_4", "related": ["八戒"]},
  {"term": "阳寿", "category": "概念", "meaning": "一个人该活的年岁。你的阳寿八十四，被借走十三年。", "firstSeen": "Node_1_5", "related": ["生死簿"]},
  {"term": "天条", "category": "概念", "meaning": "天上的规矩。天庭是抄的，真本在西天那位手里。", "firstSeen": "Node_1_3", "related": ["二郎神", "阎罗王"]},
  {"term": "取经", "category": "概念", "meaning": "唐僧师徒西行的功业。你的十三年阳寿、你女儿的名字，都记在「取经功果」的账上。", "firstSeen": "Node_1_5", "related": ["观音菩萨", "八戒", "第二十四难"]},
  {"term": "第二十四难", "category": "概念", "meaning": "取经八十一难里的一难：「高老庄收伏猪悟能」。这一难，是高太公一家写成的。", "firstSeen": "Node_2_6", "related": ["取经", "高老庄"]},
  {"term": "轮回为猪", "category": "概念", "meaning": "判官给你定的投胎去处。诽谤神明，论律轮回为猪。", "firstSeen": "Node_1_8", "related": ["六道轮回", "八戒"]},
  {"term": "明怒尊者", "category": "概念", "meaning": "观音菩萨开出的招安条件——你若皈依，封你为明怒尊者，超脱生死。", "firstSeen": "Node_3_6", "related": ["观音菩萨"]},
];