#!/usr/bin/env node
/* 把 stories/charon/nodes/*.json 同步为 stories/charon/nodes.data.ts（引擎可读的数据模块）。
   每个故事一个 nodes/ 目录 + 一个 nodes.data.ts，量产新故事时复制本脚本或改 STORIES 列表即可。
   运行：npm run sync:data */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const STORIES_DIR = join(ROOT, "stories");

const storyDirs = readdirSync(STORIES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name);

for (const storyId of storyDirs) {
  const src = join(STORIES_DIR, storyId, "nodes");
  if (!existsSync(src)) continue;
  const files = readdirSync(src).filter((f) => f.startsWith("node_") && f.endsWith(".json"));
  if (files.length === 0) continue;

  const nodes = files.sort().map((f) => JSON.parse(readFileSync(join(src, f), "utf-8")));
  const out = join(STORIES_DIR, storyId, "nodes.data.ts");
  const header = `// AUTO-GENERATED by scripts/sync_nodes.mjs — 勿手改。\n` +
    `// 源数据：stories/${storyId}/nodes/（由 generate_nodes.py 生成）\n`;
  const body =
    `import type { NodeDef } from "../../src/engine/types";\n\n` +
    `export const NODES: NodeDef[] = ${JSON.stringify(nodes, null, 2)};\n`;

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, header + body, "utf-8");
  console.log(`synced ${nodes.length} nodes -> ${out}`);
}
